const Product = [
  {
    id: 1,
    name: 'Lenovo Ideaped',
    slug: 'lenovo-ideaped',
    description: 'Short description of the product goes here',
    price: '$99.99',
    rating: 4,
    reviews: 24,
    image: '/products/1.png',
    category: 'Laptop',
  },
  {
    id: 2,
    name: 'Mouse Rexus',
    slug: 'mouse-rexus',
    description: 'Short description of the product goes here',
    price: '$149.99',
    rating: 4.5,
    reviews: 82,
    image: '/newProduct/2.png',
    category: 'Computer Accessories',
  },
  {
    id: 3,
    name: 'Advan workplus',
    slug: 'advan-workplus',
    description: 'Short description of the product goes here',
    price: '$199.99',
    rating: 4,
    reviews: 18,
    image: '/products/2.png',
    category: 'Laptop',
  },
  {
    id: 4,
    name: 'Web Company Profile',
    slug: 'web-company-profile',
    description: 'Short description of the product goes here',
    price: '$299.99',
    rating: 5,
    reviews: 127,
    image: '/newProduct/1.png',
    category: 'Web Service',
  },
  {
    id: 5,
    name: 'Web Operational',
    slug: 'web-operational',
    description: 'Short description of the product goes here',
    price: '$299.99',
    rating: 5,
    reviews: 127,
    image: '/newProduct/1.png',
    category: 'Web Service',
  },
  {
    id: 6,
    name: 'Web Katalog',
    slug: 'web-katalog',
    description: 'Short description of the product goes here',
    price: '$50',
    rating: 5,
    reviews: 127,
    image: '/newProduct/1.png',
    category: 'Web Service',
  },
  {
    id: 7,
    name: 'Keyboard Fantech',
    slug: 'keyboard-fantech',
    description: 'Short description of the product goes here',
    price: '$199.99',
    rating: 5,
    reviews: 127,
    image: '/newProduct/3.png',
    category: 'Computer Accessories',
  },
  {
    id: 8,
    name: 'PC Gaming',
    slug: 'pc-gaming',
    description: 'Short description of the product goes here',
    price: '$199.99',
    rating: 5,
    reviews: 127,
    image: '/newProduct/4.png',
    category: 'Computers',
  },
  {
    id: 9,
    name: 'CCTV Huaei',
    slug: 'cctv-huaei',
    description: 'Short description of the product goes here',
    price: '$199.99',
    rating: 5,
    reviews: 127,
    image: '/products/5.png',
    category: 'Security',
  },
  {
    id: 10,
    name: 'Game Pad Rexus',
    slug: 'game-pad-rexus',
    description: 'Short description of the product goes here',
    price: '$199.99',
    rating: 5,
    reviews: 127,
    image: '/products/6.png',
    category: 'Gaming',
  },
];

export default Product;
